create table GENDERS(
ID int  NOT NULL AUTO_INCREMENT,
NAME varchar(255) NOT NULL,
PRIMARY KEY (ID));

create table JOBS(
ID int  NOT NULL AUTO_INCREMENT,
NAME varchar(255) NOT NULL,
SALARY int NOT NULL,
PRIMARY KEY (ID));

create table EMPLOYEES(
ID int NOT NULL AUTO_INCREMENT,
GENDER_ID int,
JOB_ID int ,
NAME varchar(255),
LAST_NAME varchar(255),
BIRTHDATE DATE,
PRIMARY KEY (ID),
CONSTRAINT FK_GENDER FOREIGN KEY (GENDER_ID) REFERENCES GENDERS(ID),
CONSTRAINT FK_JOB FOREIGN KEY (JOB_ID) REFERENCES JOBS(ID));

create table EMPLOYEE_WORKED_HOURS(
ID int NOT NULL AUTO_INCREMENT,
EMPLOYEE_ID int,
WORKED_HOURS int,
WORKED_DATE varchar(255),
PRIMARY KEY (ID),
CONSTRAINT FK_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(ID));

